/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Vista.frm_historial;

import java.io.IOException;
//import javax.sound.sampled.AudioSystem;
//import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
//import javax.sound.sampled.UnsupportedAudioFileException;
import java.applet.AudioClip;



/**
 *
 * @author angeltucubal
 */
public class frm_calculadora extends javax.swing.JFrame {
    /*public Clip clip;
    public String ruta="/sonido/";
    */
    public static float pnum;
    public static float snum;
    public static String ope;
    public static String texto = "";
  //  String info;
    private Object txt_text;
    

    /**
     * Creates new form frm_calculadora
     */
    public frm_calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       frm_historial frm = new frm_historial();
       frm.show();
    }
    
    /*public void sonido(String archivo){
        try{
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ope+archivo+".wav")));
            clip.start();
        }catch(IOException | LineUnavailableException | UnsupportedAudioFileException e){
        }
        
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_escritorio = new javax.swing.JDesktopPane();
        txt_pantalla = new javax.swing.JTextField();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_mas = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dp_escritorio.setBackground(new java.awt.Color(204, 255, 255));

        txt_pantalla.setBackground(new java.awt.Color(153, 204, 255));
        txt_pantalla.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        txt_pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pantallaActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(204, 204, 204));
        btn_1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_1.setText("1");
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_1MouseEntered(evt);
            }
        });
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(204, 204, 204));
        btn_2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_2.setText("2");
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_2MouseClicked(evt);
            }
        });
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(204, 204, 204));
        btn_3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_3.setText("3");
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_3MouseClicked(evt);
            }
        });
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_mas.setBackground(new java.awt.Color(204, 204, 204));
        btn_mas.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_mas.setText("+");
        btn_mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masMouseClicked(evt);
            }
        });
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(204, 204, 204));
        btn_4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_4.setText("4");
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_4MouseClicked(evt);
            }
        });
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(204, 204, 204));
        btn_7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_7.setText("7");
        btn_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_7MouseClicked(evt);
            }
        });
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(204, 204, 204));
        btn_0.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_0.setText("0");
        btn_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_0MouseClicked(evt);
            }
        });
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(204, 204, 204));
        btn_punto.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_punto.setText(".");
        btn_punto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_puntoMouseClicked(evt);
            }
        });
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(204, 204, 204));
        btn_8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_8.setText("8");
        btn_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_8MouseClicked(evt);
            }
        });
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(204, 204, 204));
        btn_5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_5.setText("5");
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_5MouseClicked(evt);
            }
        });
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(204, 204, 204));
        btn_igual.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_igual.setText("=");
        btn_igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_igualMouseClicked(evt);
            }
        });
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(204, 204, 204));
        btn_6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_6.setText("6");
        btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_6MouseClicked(evt);
            }
        });
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(204, 204, 204));
        btn_9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_9.setText("9");
        btn_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_9MouseClicked(evt);
            }
        });
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_mult.setBackground(new java.awt.Color(204, 204, 204));
        btn_mult.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_mult.setText("*");
        btn_mult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_multMouseClicked(evt);
            }
        });
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });

        btn_menos.setBackground(new java.awt.Color(204, 204, 204));
        btn_menos.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_menos.setText("-");
        btn_menos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menosMouseClicked(evt);
            }
        });
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_div.setBackground(new java.awt.Color(204, 204, 204));
        btn_div.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_div.setText("/");
        btn_div.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_divMouseClicked(evt);
            }
        });
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btn_eliminar.setText("C");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        dp_escritorio.setLayer(txt_pantalla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_mas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_0, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_punto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_igual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_mult, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_menos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_div, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp_escritorio.setLayer(btn_eliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dp_escritorioLayout = new javax.swing.GroupLayout(dp_escritorio);
        dp_escritorio.setLayout(dp_escritorioLayout);
        dp_escritorioLayout.setHorizontalGroup(
            dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_escritorioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dp_escritorioLayout.createSequentialGroup()
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dp_escritorioLayout.createSequentialGroup()
                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dp_escritorioLayout.createSequentialGroup()
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_pantalla)
                        .addGroup(dp_escritorioLayout.createSequentialGroup()
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        dp_escritorioLayout.setVerticalGroup(
            dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Historial");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                jMenu2MenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        jMenuItem3.setText("Ayuda");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frm_ayuda frm = new frm_ayuda();
        this.dp_escritorio.add(frm);
        frm.show();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frm_historial frm = new frm_historial();
        this.dp_escritorio.add(frm);
        frm.show();
        
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txt_pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pantallaActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"1");
        //sonido("");
        
        
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"0");
        //this.txt_text.setText(this.txt_text.getText()+"0");
        //pnum = txt_pantalla2.getText();
        //frm_historial.txt_pantalla2.setText(txt_pantalla.getText()+"0");
       // pnum = btn_0.getText();
       //texto = txt_pantalla.getText();
       frm_historial frm = new frm_historial();
       frm.show();
       String info = txt_pantalla.getText();
       frm_historial.txt_text.setText(info);
       
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:
        this.pnum=Float.parseFloat(this.txt_pantalla.getText());
        this.ope="/";
        this.txt_pantalla.setText("");
        //this.pnum = txt_pantalla.getText();
        
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // TODO add your handling code here:
        if(!(this.txt_pantalla.getText().contains("."))){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+".");
        }
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_1MouseEntered

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        // TODO add your handling code here:
        this.pnum=Float.parseFloat(this.txt_pantalla.getText());
        this.ope="+";
        this.txt_pantalla.setText("");
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_masActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        // TODO add your handling code here:
        this.snum=Float.parseFloat(this.txt_pantalla.getText());

        switch(this.ope){
            case "+":this.txt_pantalla.setText(sincero(this.pnum+this.snum)); break;
            case "-":this.txt_pantalla.setText(sincero(this.pnum-this.snum)); break;
            case "*":this.txt_pantalla.setText(sincero(this.pnum*this.snum)); break;
            case "/":if(this.snum==0){this.txt_pantalla.setText("NoSeDivideEntreCero");}
            else{
                this.txt_pantalla.setText(sincero(this.pnum/this.snum));} break;
        }
        
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        // TODO add your handling code here:
        this.pnum=Float.parseFloat(this.txt_pantalla.getText());
        this.ope="-";
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
        // TODO add your handling code here:
        this.pnum=Float.parseFloat(this.txt_pantalla.getText());
        this.ope="*";
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"8");

    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
        
    }//GEN-LAST:event_btn_1MouseClicked

    private void btn_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_2MouseClicked

    private void btn_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_3MouseClicked

    private void btn_masMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masMouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_masMouseClicked

    private void btn_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_4MouseClicked

    private void btn_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_5MouseClicked

    private void btn_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_6MouseClicked

    private void btn_menosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menosMouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_menosMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_7MouseClicked

    private void btn_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_8MouseClicked

    private void btn_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_9MouseClicked

    private void btn_multMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multMouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_multMouseClicked

    private void btn_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_0MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_0MouseClicked

    private void btn_puntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_puntoMouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_puntoMouseClicked

    private void btn_igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_igualMouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_igualMouseClicked

    private void btn_divMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_divMouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_divMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenu2MenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuCanceled
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jMenu2MenuCanceled

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Vista/tono de notificaciÃ³n Twitter.wav"));
        Sound.play();
    }//GEN-LAST:event_jMenu2MouseClicked

    public String sincero(float resultado){
    String retorno=" ";
    retorno=Float.toString(resultado);
    if(resultado%1==0){
        retorno=retorno.substring(0, retorno.length()-2);
    }
            return retorno;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_punto;
    private javax.swing.JDesktopPane dp_escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JTextField txt_pantalla;
    // End of variables declaration//GEN-END:variables
}
